# Generated by Django 4.1 on 2023-01-10 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('effectiveFrom', models.DateTimeField(blank=True, null=True)),
                ('effectiveTo', models.DateTimeField(blank=True, null=True)),
                ('lastUpdated', models.DateTimeField()),
                ('productCategory', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=120)),
                ('brandName', models.CharField(blank=True, max_length=120, null=True)),
                ('applicationUri', models.CharField(blank=True, max_length=255, null=True)),
                ('isTailored', models.BooleanField()),
                ('additionalInformationOverviewUri', models.CharField(blank=True, max_length=255, null=True)),
                ('additionalInformationTermsUri', models.CharField(blank=True, max_length=255, null=True)),
                ('additionalInformationEligibilityUri', models.CharField(blank=True, max_length=255, null=True)),
                ('additionalInformationFeesAndPricingUri', models.CharField(blank=True, max_length=255, null=True)),
                ('additionalInformationBundleUri', models.CharField(blank=True, max_length=255, null=True)),
                ('additionalInformationAdditionalOverviewUri', models.CharField(blank=True, max_length=255, null=True)),
                ('additionalInformationAdditionalTermsUri', models.CharField(blank=True, max_length=255, null=True)),
                ('additionalInformationAdditionalEligibilityUri', models.CharField(blank=True, max_length=255, null=True)),
                ('additionalInformationAdditionalFeesAndPricingUri', models.CharField(blank=True, max_length=255, null=True)),
                ('additionalInformationAdditionalBundleUri', models.CharField(blank=True, max_length=255, null=True)),
                ('insertTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LendingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lendingRateType', models.CharField(max_length=120)),
                ('rate', models.CharField(max_length=120)),
                ('comparisonRate', models.CharField(blank=True, max_length=120, null=True)),
                ('calculationFrequency', models.CharField(blank=True, max_length=120, null=True)),
                ('applicationFrequency', models.CharField(blank=True, max_length=120, null=True)),
                ('interestPaymentDue', models.CharField(blank=True, max_length=120, null=True)),
                ('repaymentType', models.CharField(blank=True, max_length=120, null=True)),
                ('loanPurpose', models.CharField(blank=True, max_length=120, null=True)),
                ('tiersName', models.CharField(blank=True, max_length=120, null=True)),
                ('tiersUnitOfMeasure', models.CharField(blank=True, max_length=120, null=True)),
                ('tiersMinimumValue', models.CharField(blank=True, max_length=120, null=True)),
                ('tiersMaximumValue', models.CharField(blank=True, max_length=120, null=True)),
                ('tiersRateApplicationMethod', models.CharField(blank=True, max_length=120, null=True)),
                ('tiersApplicabilityConditionsAdditionalInfo', models.CharField(blank=True, max_length=255, null=True)),
                ('tiersApplicabilityConditionsAdditionalInfoUri', models.CharField(blank=True, max_length=255, null=True)),
                ('tiersAdditionalInfo', models.CharField(blank=True, max_length=255, null=True)),
                ('tiersAdditionalInfoUri', models.CharField(blank=True, max_length=255, null=True)),
                ('additionalValue', models.CharField(max_length=255)),
                ('additionalInfo', models.CharField(blank=True, max_length=255, null=True)),
                ('additionalInfoUri', models.CharField(blank=True, max_length=255, null=True)),
                ('insertTime', models.DateTimeField()),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lendingRates', to='products.product')),
            ],
        ),
    ]
