# Generated by Django 4.1 on 2022-12-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, serialize=False, verbose_name='ID')),
                ('product_id', models.UUIDField(max_length=120, primary_key=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField()),
                ('last_updated', models.DateField()),
                ('product_category', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=120)),
                ('brand_name', models.CharField(max_length=120)),
                ('application_uri', models.TextField(max_length=255)),
                ('is_tailored', models.CharField(max_length=120)),
                ('additional_information_overview_uri', models.TextField(max_length=255)),
                ('additional_information_terms_uri', models.TextField(max_length=255)),
                ('additional_information_eligibility_uri', models.TextField(max_length=255)),
                ('additional_information_fees_and_pricing_uri', models.TextField(max_length=255)),
                ('additional_information_bundle_uri', models.TextField(max_length=255)),
                ('insert_time', models.DateField()),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
