from django.db import models


class Customer(models.Model):
  customer_number = models.BigIntegerField(primary_key=True)
  customer_utype = models.CharField(max_length=120, null=True, blank=True)
  last_update_time = models.DateTimeField(null=True, blank=True)
  person_first_name = models.CharField(max_length=120, null=True, blank=True)
  person_last_name = models.CharField(max_length=120, null=True, blank=True)
  person_middle_name1 = models.CharField(max_length=120, null=True, blank=True)
  person_middle_name2 = models.CharField(max_length=120, null=True, blank=True)
  person_middle_name3 = models.CharField(max_length=120, null=True, blank=True)
  person_prefix = models.CharField(max_length=120, null=True, blank=True)
  person_suffix = models.CharField(max_length=120, null=True, blank=True)
  person_occupation_code = models.CharField(max_length=120, null=True, blank=True)
  person_occupation_code_version = models.CharField(max_length=120, null=True, blank=True)
  organization_agent_first_name = models.CharField(max_length=120, null=True, blank=True)
  organization_agent_last_name = models.CharField(max_length=120, null=True, blank=True)
  organization_agent_role = models.CharField(max_length=120, null=True, blank=True)
  organization_business_name = models.CharField(max_length=120, null=True, blank=True)
  organization_agent_first_name = models.CharField(max_length=120, null=True, blank=True)
  organization_legal_name = models.CharField(max_length=120, null=True, blank=True)
  organization_short_name = models.CharField(max_length=120, null=True, blank=True)
  organization_abn = models.CharField(max_length=120, null=True, blank=True)
  organization_acn = models.CharField(max_length=120, null=True, blank=True)
  organization_is_acn_registered = models.BooleanField()
  organization_industry_code = models.CharField(max_length=120, null=True, blank=True)
  organization_industry_code_version = models.CharField(max_length=120, null=True, blank=True)
  organization_type = models.CharField(max_length=120, null=True, blank=True)
  organization_registered_country = models.CharField(max_length=120, null=True, blank=True)
  organization_establishment_date = models.DateTimeField(null=True, blank=True)
  email_address = models.CharField(max_length=120, null=True, blank=True)
  is_preferred = models.BooleanField()
  purpose = models.CharField(max_length=120, null=True, blank=True)
  birth_date = models.DateField(null=True, blank=True)
  insert_time = models.DateTimeField()

  def __str__(self):
    return self.person_last_name

class CustomerPhoneNumber(models.Model):
  customer = models.ForeignKey(Customer, related_name='phone_number', on_delete=models.CASCADE)
  is_preferred = models.BooleanField()
  purpose = models.CharField(max_length=120, null=True, blank=True)
  country_code = models.CharField(max_length=120, null=True, blank=True)
  area_code = models.CharField(max_length=120, null=True, blank=True)
  number = models.CharField(max_length=120, null=True, blank=True)
  extension = models.CharField(max_length=120, null=True, blank=True)
  full_number = models.CharField(max_length=120, null=True, blank=True)
  insert_time = models.DateTimeField()

  def __str__(self):
    return self.full_number

class CustomerPhysicalAddress(models.Model):
  customer = models.ForeignKey(Customer, related_name='physical_address', on_delete=models.CASCADE)
  address_utype = models.CharField(max_length=120, null=True, blank=True)
  simple_mailing_name = models.CharField(max_length=120, null=True, blank=True)
  simple_address_line1 = models.CharField(max_length=120, null=True, blank=True)
  simple_address_line2 = models.CharField(max_length=120, null=True, blank=True)
  simple_address_line3 = models.CharField(max_length=120, null=True, blank=True)
  simple_post_code = models.CharField(max_length=120, null=True, blank=True)
  simple_city = models.CharField(max_length=120, null=True, blank=True)
  simple_state = models.CharField(max_length=120, null=True, blank=True)
  simple_country = models.CharField(max_length=120, null=True, blank=True)
  paf_dpid = models.CharField(max_length=120, null=True, blank=True)
  paf_thoroughfare_number1 = models.PositiveIntegerField(null=True, blank=True)
  paf_thoroughfare_number1_suffix = models.CharField(max_length=120, null=True, blank=True)
  paf_thoroughfare_number2 = models.PositiveIntegerField(null=True, blank=True)
  paf_thoroughfare_number2_suffix = models.CharField(max_length=120, null=True, blank=True)
  paf_flat_unit_type = models.CharField(max_length=120, null=True, blank=True)
  paf_flat_unit_number = models.CharField(max_length=120, null=True, blank=True)
  paf_floor_level_type = models.CharField(max_length=120, null=True, blank=True)
  paf_floor_level_number = models.CharField(max_length=120, null=True, blank=True)
  paf_lot_number = models.CharField(max_length=120, null=True, blank=True)
  paf_building_name1 = models.CharField(max_length=120, null=True, blank=True)
  paf_building_name2 = models.CharField(max_length=120, null=True, blank=True)
  paf_street_name = models.CharField(max_length=120, null=True, blank=True)
  paf_street_type = models.CharField(max_length=120, null=True, blank=True)
  paf_street_suffix = models.CharField(max_length=120, null=True, blank=True)
  paf_postal_delivery_type = models.CharField(max_length=120, null=True, blank=True)
  paf_postal_delivery_number = models.PositiveIntegerField(null=True, blank=True)
  paf_postal_delivery_number_prefix = models.CharField(max_length=120, null=True, blank=True)
  paf_postal_delivery_number_suffix = models.CharField(max_length=120, null=True, blank=True)
  paf_locality_name = models.CharField(max_length=120, null=True, blank=True)
  paf_postcode = models.CharField(max_length=120, null=True, blank=True)
  paf_state = models.CharField(max_length=120, null=True, blank=True)
  purpose = models.CharField(max_length=120, null=True, blank=True)
  insert_time = models.DateTimeField()

  def __str__(self):
    return self.simple_address_line1