# Generated by Django 4.1 on 2023-02-18 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('customer_utype', models.CharField(blank=True, max_length=120, null=True)),
                ('last_update_time', models.DateTimeField(blank=True, null=True)),
                ('person_first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('person_last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('person_middle_name1', models.CharField(blank=True, max_length=120, null=True)),
                ('person_middle_name2', models.CharField(blank=True, max_length=120, null=True)),
                ('person_middle_name3', models.CharField(blank=True, max_length=120, null=True)),
                ('person_prefix', models.CharField(blank=True, max_length=120, null=True)),
                ('person_suffix', models.CharField(blank=True, max_length=120, null=True)),
                ('person_occupation_code', models.CharField(blank=True, max_length=120, null=True)),
                ('person_occupation_code_version', models.CharField(blank=True, max_length=120, null=True)),
                ('organization_agent_last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('organization_agent_role', models.CharField(blank=True, max_length=120, null=True)),
                ('organization_business_name', models.CharField(blank=True, max_length=120, null=True)),
                ('organization_agent_first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('organization_legal_name', models.CharField(blank=True, max_length=120, null=True)),
                ('organization_short_name', models.CharField(blank=True, max_length=120, null=True)),
                ('organization_abn', models.CharField(blank=True, max_length=120, null=True)),
                ('organization_acn', models.CharField(blank=True, max_length=120, null=True)),
                ('organization_is_acn_registered', models.BooleanField()),
                ('organization_industry_code', models.CharField(blank=True, max_length=120, null=True)),
                ('organization_industry_code_version', models.CharField(blank=True, max_length=120, null=True)),
                ('organization_type', models.CharField(blank=True, max_length=120, null=True)),
                ('organization_registered_country', models.CharField(blank=True, max_length=120, null=True)),
                ('organization_establishment_date', models.DateTimeField(blank=True, null=True)),
                ('email_address', models.CharField(blank=True, max_length=120, null=True)),
                ('is_preferred', models.BooleanField()),
                ('purpose', models.CharField(blank=True, max_length=120, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('last_modified_time', models.DateTimeField(blank=True, null=True)),
                ('insert_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPhysicalAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_utype', models.CharField(blank=True, max_length=120, null=True)),
                ('simple_mailing_name', models.CharField(blank=True, max_length=120, null=True)),
                ('simple_address_line1', models.CharField(blank=True, max_length=120, null=True)),
                ('simple_address_line2', models.CharField(blank=True, max_length=120, null=True)),
                ('simple_address_line3', models.CharField(blank=True, max_length=120, null=True)),
                ('simple_post_code', models.CharField(blank=True, max_length=120, null=True)),
                ('simple_city', models.CharField(blank=True, max_length=120, null=True)),
                ('simple_state', models.CharField(blank=True, max_length=120, null=True)),
                ('simple_country', models.CharField(blank=True, max_length=120, null=True)),
                ('paf_dpid', models.CharField(blank=True, max_length=120, null=True)),
                ('paf_thoroughfare_number1', models.PositiveIntegerField(blank=True, null=True)),
                ('paf_thoroughfare_number1_suffix', models.CharField(blank=True, max_length=120, null=True)),
                ('paf_thoroughfare_number2', models.PositiveIntegerField(blank=True, null=True)),
                ('paf_thoroughfare_number2_suffix', models.CharField(blank=True, max_length=120, null=True)),
                ('paf_flat_unit_type', models.CharField(blank=True, max_length=120, null=True)),
                ('paf_flat_unit_number', models.CharField(blank=True, max_length=120, null=True)),
                ('paf_floor_level_type', models.CharField(blank=True, max_length=120, null=True)),
                ('paf_floor_level_number', models.CharField(blank=True, max_length=120, null=True)),
                ('paf_lot_number', models.CharField(blank=True, max_length=120, null=True)),
                ('paf_building_name1', models.CharField(blank=True, max_length=120, null=True)),
                ('paf_building_name2', models.CharField(blank=True, max_length=120, null=True)),
                ('paf_street_name', models.CharField(blank=True, max_length=120, null=True)),
                ('paf_street_type', models.CharField(blank=True, max_length=120, null=True)),
                ('paf_street_suffix', models.CharField(blank=True, max_length=120, null=True)),
                ('paf_postal_delivery_type', models.CharField(blank=True, max_length=120, null=True)),
                ('paf_postal_delivery_number', models.PositiveIntegerField(blank=True, null=True)),
                ('paf_postal_delivery_number_prefix', models.CharField(blank=True, max_length=120, null=True)),
                ('paf_postal_delivery_number_suffix', models.CharField(blank=True, max_length=120, null=True)),
                ('paf_locality_name', models.CharField(blank=True, max_length=120, null=True)),
                ('paf_postcode', models.CharField(blank=True, max_length=120, null=True)),
                ('paf_state', models.CharField(blank=True, max_length=120, null=True)),
                ('purpose', models.CharField(blank=True, max_length=120, null=True)),
                ('last_modified_time', models.DateTimeField(blank=True, null=True)),
                ('insert_time', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_address', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_preferred', models.BooleanField()),
                ('purpose', models.CharField(blank=True, max_length=120, null=True)),
                ('country_code', models.CharField(blank=True, max_length=120, null=True)),
                ('area_code', models.CharField(blank=True, max_length=120, null=True)),
                ('number', models.CharField(blank=True, max_length=120, null=True)),
                ('extension', models.CharField(blank=True, max_length=120, null=True)),
                ('full_number', models.CharField(blank=True, max_length=120, null=True)),
                ('last_modified_time', models.DateTimeField(blank=True, null=True)),
                ('insert_time', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_number', to='customers.customer')),
            ],
        ),
    ]
