# Generated by Django 4.1 on 2023-02-18 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_modified_time',
        ),
        migrations.RemoveField(
            model_name='customerphonenumber',
            name='last_modified_time',
        ),
        migrations.RemoveField(
            model_name='customerphysicaladdress',
            name='last_modified_time',
        ),
    ]
